"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
type Member={id:string;name_ar:string;role:string};
type EventItem={id:string;title:string;note:string;memberId:string;memberName:string;category:string;startsAt:string;reminder:number};
const colors:Record<string,string>={"عائلة":"#fbbf24","مدرسة":"#86efac","جامعة":"#7dd3fc","صحة":"#f9a8d4","موعد":"#c4b5fd"};
export default function FamilyCalendarPage(){
 const router=useRouter();const [events,setEvents]=useState<EventItem[]>([]);const [members,setMembers]=useState<Member[]>([]);const [canManage,setCanManage]=useState(false);const [loading,setLoading]=useState(true);const [message,setMessage]=useState("");
 const tomorrow=new Date(Date.now()+86400000);tomorrow.setMinutes(0,0,0);
 const [form,setForm]=useState({title:"",note:"",memberId:"all",category:"عائلة",startsAt:"",reminder:30});
 const load=useCallback(async()=>{const r=await fetch("/api/family/calendar",{cache:"no-store"});const d=await r.json();if(!r.ok){setMessage(d.error??"تعذر تحميل التقويم");setLoading(false);return}setEvents(d.events??[]);setMembers(d.members??[]);setCanManage(Boolean(d.canManage));setLoading(false)},[]);useEffect(()=>{void load()},[load]);
 async function create(e:React.FormEvent){e.preventDefault();const r=await fetch("/api/family/calendar",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const d=await r.json();if(!r.ok){setMessage(d.error??"تعذر حفظ الموعد");return}setForm({...form,title:"",note:""});setMessage("تم حفظ الموعد والتذكير.");await load()}
 async function remove(id:string){const r=await fetch("/api/family/calendar",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({id})});const d=await r.json();if(!r.ok){setMessage(d.error??"تعذر الحذف");return}setEvents(x=>x.filter(e=>e.id!==id));setMessage("تم حذف الموعد.")}
 const upcoming=useMemo(()=>events.filter(e=>new Date(e.startsAt).getTime()>=Date.now()),[events]);const past=useMemo(()=>events.filter(e=>new Date(e.startsAt).getTime()<Date.now()).slice(-8).reverse(),[events]);
 const alerts=useMemo(()=>upcoming.filter(e=>new Date(e.startsAt).getTime()-Date.now()<=7*86400000).slice(0,6),[upcoming]);
 const remainingText=(value:string)=>{const diff=new Date(value).getTime()-Date.now();const minutes=Math.max(0,Math.ceil(diff/60000));if(minutes<60)return `باقي ${minutes} دقيقة`;const hours=Math.ceil(minutes/60);if(hours<24)return `باقي ${hours} ساعة`;const days=Math.ceil(hours/24);return `باقي ${days} يوم`;};
 const dateText=(value:string)=>new Intl.DateTimeFormat("ar-AE",{weekday:"short",day:"numeric",month:"short",hour:"2-digit",minute:"2-digit"}).format(new Date(value));
 if(loading)return <main dir="rtl" className="flex min-h-screen items-center justify-center bg-[#03040a] text-white">جاري تجهيز تقويم العائلة…</main>;
 return <main dir="rtl" className="min-h-screen bg-[#03040a] px-4 py-7 text-white sm:px-6"><div className="mx-auto max-w-7xl"><header className="flex flex-wrap items-center justify-between gap-4 border-b border-white/10 pb-6"><div><p className="text-xs font-black tracking-[.3em] text-violet-200/55">FAMILY CALENDAR</p><h1 className="mt-2 text-4xl font-black">تقويم العائلة 📅</h1><p className="mt-2 text-sm text-white/40">المواعيد والتنبيهات في مكان واحد</p></div><button onClick={()=>router.push("/v9/home")} className="rounded-2xl border border-white/10 px-5 py-3">البيت الرقمي</button></header>
 {message&&<p className="mt-5 rounded-2xl bg-violet-300/10 p-4 text-violet-100">{message}</p>}
 <section className="mt-6 rounded-[30px] border border-amber-200/15 bg-amber-300/[.035] p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-black tracking-[.25em] text-amber-200/55">SMART ALERTS</p><h2 className="mt-2 text-2xl font-black">مركز التنبيهات العائلية 🔔</h2></div><span className="rounded-full bg-amber-300/10 px-4 py-2 text-xs font-black text-amber-100">{alerts.length} تنبيه قريب</span></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{alerts.length===0?<div className="rounded-2xl border border-white/10 bg-black/20 p-5 text-sm text-white/40">لا توجد تنبيهات خلال الأيام السبعة القادمة.</div>:alerts.map(event=><article key={`alert-${event.id}`} className="rounded-2xl border border-white/10 bg-black/25 p-4"><div className="flex items-center justify-between gap-3"><span className="rounded-full px-3 py-1 text-[10px] font-bold" style={{color:colors[event.category],background:`${colors[event.category]}18`}}>{event.category}</span><strong className="text-xs text-amber-200">{remainingText(event.startsAt)}</strong></div><h3 className="mt-3 font-black">{event.title}</h3><p className="mt-2 text-xs text-white/40">{event.memberName} • {dateText(event.startsAt)}</p><p className="mt-3 text-[11px] text-violet-200/55">يُنبه قبل {event.reminder>=1440?"يوم":event.reminder>=60?"ساعة":`${event.reminder} دقيقة`}</p></article>)}</div></section>
 <section className="mt-6 grid gap-5 lg:grid-cols-[.75fr_1.25fr]"><form onSubmit={create} className="h-fit rounded-[30px] border border-violet-200/10 bg-violet-300/[.035] p-5"><h2 className="text-2xl font-black">إضافة موعد</h2><input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="اسم الموعد أو التذكير" className="mt-4 w-full rounded-2xl bg-[#10131c] p-4" required/><textarea value={form.note} onChange={e=>setForm({...form,note:e.target.value})} placeholder="ملاحظات اختيارية" className="mt-3 w-full rounded-2xl bg-[#10131c] p-4" rows={3}/>{canManage&&<select value={form.memberId} onChange={e=>setForm({...form,memberId:e.target.value})} className="mt-3 w-full rounded-2xl bg-[#10131c] p-4"><option value="all">جميع أفراد العائلة</option>{members.map(m=><option key={m.id} value={m.id}>{m.name_ar}</option>)}</select>}<div className="mt-3 grid grid-cols-2 gap-3"><select value={form.category} onChange={e=>setForm({...form,category:e.target.value})} className="rounded-2xl bg-[#10131c] p-4">{Object.keys(colors).map(c=><option key={c}>{c}</option>)}</select><select value={form.reminder} onChange={e=>setForm({...form,reminder:Number(e.target.value)})} className="rounded-2xl bg-[#10131c] p-4"><option value={10}>قبل 10 دقائق</option><option value={30}>قبل 30 دقيقة</option><option value={60}>قبل ساعة</option><option value={1440}>قبل يوم</option></select></div><input type="datetime-local" value={form.startsAt} onChange={e=>setForm({...form,startsAt:e.target.value})} className="mt-3 w-full rounded-2xl bg-[#10131c] p-4" required/><button className="mt-4 w-full rounded-2xl bg-violet-300 p-4 font-black text-black">حفظ الموعد</button></form>
 <div><div className="flex items-center justify-between"><h2 className="text-2xl font-black">القادم</h2><span className="rounded-full bg-white/5 px-3 py-2 text-xs">{upcoming.length} موعد</span></div><div className="mt-4 space-y-3">{upcoming.length===0?<div className="rounded-[28px] border border-white/10 bg-white/[.03] p-8 text-center text-white/35">لا توجد مواعيد قادمة.</div>:upcoming.map((event,index)=><article key={event.id} className="rounded-[26px] border border-white/10 bg-white/[.03] p-5" style={{borderRightColor:colors[event.category],borderRightWidth:4}}><div className="flex flex-wrap justify-between gap-3"><div><span className="rounded-full px-3 py-1 text-[10px]" style={{color:colors[event.category],background:`${colors[event.category]}18`}}>{event.category}</span><h3 className="mt-3 text-xl font-black">{event.title}</h3><p className="mt-2 text-sm text-white/40">{event.memberName} • {dateText(event.startsAt)}</p>{event.note&&<p className="mt-2 text-sm text-white/35">{event.note}</p>}</div><div className="text-left">{index===0&&<span className="block rounded-full bg-amber-300/10 px-3 py-1 text-[10px] text-amber-200">الموعد القادم</span>}<button onClick={()=>void remove(event.id)} className="mt-3 text-xs text-rose-200">حذف</button></div></div><p className="mt-3 text-[11px] text-violet-200/55">تنبيه قبل {event.reminder>=1440?"يوم":event.reminder>=60?"ساعة":`${event.reminder} دقيقة`}</p></article>)}</div></div></section>
 {past.length>0&&<section className="mt-6 rounded-[28px] border border-white/10 bg-white/[.025] p-5"><h2 className="text-xl font-black">مواعيد سابقة</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{past.map(e=><div key={e.id} className="rounded-2xl bg-black/20 p-4 opacity-60"><strong>{e.title}</strong><p className="mt-2 text-xs text-white/40">{dateText(e.startsAt)}</p></div>)}</div></section>}
 </div></main>}
