"use client";
import { useCallback, useEffect, useState } from "react";
import { useRouter } from "next/navigation";

type Child = { id: string; name_ar: string };
type Reward = { id: string; title: string; cost: number; priceAed?: number; imageUrl?: string };
type RequestItem = Reward & { childId: string; childName: string; status: string };
type History = { id: string; title: string; childName: string; points: number };

export default function RewardsPage() {
  const router = useRouter(); const [loading,setLoading]=useState(true); const [message,setMessage]=useState("");
  const [canManage,setCanManage]=useState(false); const [viewer,setViewer]=useState<{id:string;name_ar:string}|null>(null);
  const [children,setChildren]=useState<Child[]>([]); const [balances,setBalances]=useState<Record<string,number>>({}); const [catalog,setCatalog]=useState<Reward[]>([]); const [requests,setRequests]=useState<RequestItem[]>([]); const [history,setHistory]=useState<History[]>([]);
  const [editedBalances,setEditedBalances]=useState<Record<string,number>>({});
  const [grant,setGrant]=useState({childId:"",reason:"ترتيب الغرفة",points:10}); const [reward,setReward]=useState({title:"30 دقيقة ألعاب إضافية",cost:50});
  const load=useCallback(async()=>{const r=await fetch("/api/family/rewards",{cache:"no-store"});const d=await r.json();if(!r.ok){setMessage(d.error??"تعذر التحميل");setLoading(false);return}setCanManage(d.canManage);setViewer(d.viewer);setChildren(d.children??[]);setBalances(d.balances??{});setCatalog(d.catalog??[]);setRequests(d.requests??[]);setHistory(d.history??[]);setGrant(g=>({...g,childId:g.childId||d.children?.[0]?.id||""}));setLoading(false)},[]);
  useEffect(()=>{void load()},[load]);
  async function send(body:Record<string,unknown>){setMessage("");const r=await fetch("/api/family/rewards",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const d=await r.json();if(!r.ok){setMessage(d.error??"تعذر تنفيذ العملية");return false}await load();return true}
  if(loading)return <main dir="rtl" className="flex min-h-screen items-center justify-center bg-[#03040a] text-white">جاري تجهيز المكافآت…</main>;
  const myBalance=viewer?balances[viewer.id]??0:0;
  return <main dir="rtl" className="min-h-screen bg-[#03040a] px-4 py-7 text-white sm:px-6"><div className="mx-auto max-w-7xl">
    <header className="flex flex-wrap items-center justify-between gap-4 border-b border-white/10 pb-6"><div><p className="text-xs font-black tracking-[.3em] text-amber-200/55">FAMILY REWARDS</p><h1 className="mt-2 text-4xl font-black">نجوم العائلة ⭐</h1><p className="mt-2 text-sm text-white/40">النقاط والتشجيع والمكافآت</p></div><button onClick={()=>router.push("/v9/home")} className="rounded-2xl border border-white/10 px-5 py-3">البيت الرقمي</button></header>
    {message&&<p className="mt-5 rounded-2xl bg-amber-300/10 p-4 text-amber-100">{message}</p>}
    <section className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{canManage?children.map(c=>{const value=editedBalances[c.id]??balances[c.id]??0;return <div key={c.id} className="rounded-[26px] border border-amber-200/15 bg-amber-300/[.05] p-5"><p className="text-sm text-white/45">{c.name_ar}</p><strong className="mt-2 block text-4xl text-amber-200">{balances[c.id]??0}</strong><span className="text-xs text-white/30">نقطة</span><input aria-label={`عداد ${c.name_ar}`} type="number" min={0} value={value} onChange={e=>setEditedBalances({...editedBalances,[c.id]:Math.max(0,Number(e.target.value)||0)})} className="mt-4 w-full rounded-xl border border-white/10 bg-black/25 px-3 py-2 text-center text-lg font-black"/><div className="mt-2 grid grid-cols-2 gap-2"><button type="button" onClick={async()=>{if(await send({action:"set_balance",childId:c.id,value}))setMessage(`تم تغيير عداد ${c.name_ar}.`)}} className="rounded-xl bg-amber-300 px-3 py-2 text-xs font-black text-black">تغيير</button><button type="button" onClick={async()=>{setEditedBalances({...editedBalances,[c.id]:0});if(await send({action:"set_balance",childId:c.id,value:0}))setMessage(`تم تصفير عداد ${c.name_ar}.`)}} className="rounded-xl bg-rose-300/15 px-3 py-2 text-xs font-black text-rose-100">تصفير</button></div></div>}):<div className="rounded-[26px] border border-amber-200/15 bg-amber-300/[.05] p-5"><p className="text-sm text-white/45">رصيدي</p><strong className="mt-2 block text-4xl text-amber-200">{myBalance}</strong><span className="text-xs text-white/30">نقطة</span></div>}</section>
    {canManage&&<div className="mt-4 flex justify-end"><button type="button" onClick={async()=>{if(window.confirm("هل تريد تصفير عدادات جميع الأطفال؟")&&await send({action:"reset_all_balances"})){setEditedBalances({});setMessage("تم تصفير جميع العدادات.")}}} className="rounded-xl border border-rose-200/20 bg-rose-300/10 px-4 py-3 text-sm font-black text-rose-100">تصفير جميع العدادات</button></div>}
    {canManage&&<section className="mt-6 grid gap-5 lg:grid-cols-2"><form onSubmit={async e=>{e.preventDefault();if(await send({action:"grant",...grant}))setMessage("تم حفظ النقاط.")}} className="rounded-[28px] border border-emerald-200/10 bg-emerald-300/[.035] p-5"><h2 className="text-2xl font-black">منح نقاط</h2><select value={grant.childId} onChange={e=>setGrant({...grant,childId:e.target.value})} className="mt-4 w-full rounded-2xl bg-[#10131c] p-4">{children.map(c=><option key={c.id} value={c.id}>{c.name_ar}</option>)}</select><input value={grant.reason} onChange={e=>setGrant({...grant,reason:e.target.value})} placeholder="سبب النقاط" className="mt-3 w-full rounded-2xl bg-[#10131c] p-4"/><div className="mt-3 grid grid-cols-4 gap-2">{[5,10,20,50].map(n=><button type="button" key={n} onClick={()=>setGrant({...grant,points:n})} className={`rounded-xl p-3 ${grant.points===n?"bg-emerald-300 text-black":"bg-white/5"}`}>+{n}</button>)}</div><button className="mt-4 w-full rounded-2xl bg-emerald-300 p-4 font-black text-black">إضافة النقاط</button></form>
    <form onSubmit={async e=>{e.preventDefault();if(await send({action:"catalog",...reward}))setMessage("تمت إضافة المكافأة.")}} className="rounded-[28px] border border-violet-200/10 bg-violet-300/[.035] p-5"><h2 className="text-2xl font-black">إضافة مكافأة</h2><input value={reward.title} onChange={e=>setReward({...reward,title:e.target.value})} placeholder="اسم المكافأة" className="mt-4 w-full rounded-2xl bg-[#10131c] p-4"/><input type="number" min={1} value={reward.cost} onChange={e=>setReward({...reward,cost:Number(e.target.value)})} className="mt-3 w-full rounded-2xl bg-[#10131c] p-4"/><button className="mt-4 w-full rounded-2xl bg-violet-300 p-4 font-black text-black">إضافة إلى متجر المكافآت</button></form></section>}
    <section className="mt-6 grid gap-5 lg:grid-cols-[1.1fr_.9fr]"><article className="rounded-[28px] border border-white/10 bg-white/[.03] p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-2xl font-black">متجر المكافآت</h2><p className="mt-1 text-xs font-bold text-amber-200/60">كل 100 نقطة = درهم واحد</p></div>{canManage&&<button onClick={async()=>{if(await send({action:"import_neighborhood_store"}))setMessage("تم تحديث منتجات دكان الحارة.")}} className="rounded-xl border border-amber-200/20 bg-amber-300/10 px-4 py-2 text-xs font-black text-amber-100">تحديث كتالوج دكان الحارة</button>}</div><div className="mt-4 grid gap-3 sm:grid-cols-2">{catalog.length===0?<p className="text-white/35">لم يضف الوالدان مكافآت بعد.</p>:catalog.map(r=>{const balance=canManage?(balances[grant.childId]??0):myBalance;const remaining=Math.max(r.cost-balance,0);return <div key={r.id} className="overflow-hidden rounded-2xl border border-white/8 bg-black/20">{r.imageUrl&&<img src={r.imageUrl} alt={r.title} className="h-36 w-full bg-white/5 object-cover"/>}<div className="p-4"><strong>{r.title}</strong>{r.priceAed?<p className="mt-1 text-xs text-white/45">سعر الدكان: {r.priceAed} د.إ</p>:null}<p className="mt-2 text-2xl font-black text-amber-200">{r.cost} نقطة</p><p className={`mt-2 rounded-xl px-3 py-2 text-sm font-black ${remaining===0?"bg-emerald-300/15 text-emerald-200":"bg-rose-300/10 text-rose-200"}`}>{remaining===0?"جاهز للاستبدال 🎉":`باقي ${remaining} نقطة للوصول`}</p><button onClick={()=>void send({action:"request",rewardId:r.id,childId:canManage?grant.childId:undefined})} disabled={remaining>0} className="mt-3 rounded-xl bg-amber-300 px-4 py-2 text-xs font-black text-black disabled:cursor-not-allowed disabled:opacity-30">طلب المكافأة</button></div></div>})}</div></article>
    <article className="rounded-[28px] border border-white/10 bg-white/[.03] p-5"><h2 className="text-2xl font-black">طلبات الاستبدال</h2><p className="mt-2 text-xs leading-6 text-white/35">بعد الموافقة تُضاف المكافأة تلقائيًا إلى قائمة مشتريات البيت باسم الطفل.</p><div className="mt-4 space-y-3">{requests.length===0?<p className="text-white/35">لا توجد طلبات حاليًا.</p>:requests.map(r=><div key={r.id} className="rounded-2xl bg-black/20 p-4"><div className="flex justify-between"><strong>{r.title}</strong><span className="text-amber-200">{r.cost}</span></div><p className="mt-1 text-xs text-white/40">{r.childName} • {r.status==="pending"?"بانتظار الموافقة":"تمت الموافقة وإضافتها للمشتريات"}</p>{canManage&&r.status==="pending"&&<button onClick={()=>void send({action:"approve",id:r.id})} className="mt-3 rounded-xl bg-emerald-300 px-4 py-2 text-xs font-black text-black">موافقة وخصم النقاط</button>}</div>)}</div></article></section>
    <section className="mt-6 rounded-[28px] border border-white/10 bg-white/[.03] p-5"><h2 className="text-xl font-black">آخر النقاط</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{history.map(h=><div key={h.id} className="rounded-2xl bg-black/20 p-4"><strong>{h.title}</strong><p className="mt-2 text-sm text-white/40">{h.childName}</p><span className={`mt-2 block text-xl font-black ${h.points>=0?"text-emerald-200":"text-rose-200"}`}>{h.points>0?"+":""}{h.points}</span></div>)}</div></section>
  </div></main>
}
